#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

use Symfony\Component\Console\Application;

$application = new Application('Inplace', file_get_contents(__DIR__ . "/VERSION"));
$application->add(new Inplace\Command\AddPackageCommand());
$application->run();
