#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

function determine_version() {
    if (Phar::running()) {
        return "@package_version@";
    }

    return file_get_contents(__DIR__ . "/VERSION")."Installed via composer global.";
}

use Symfony\Component\Console\Application;

$application = new Application('Inplace', determine_version() );
$application->add(new Inplace\Command\AddPackageCommand());
$application->run();
